services:
  
  # SERVICE DISCOVERY #
  eureka:
    extends:
      file: ./eureka/eureka.yml
      service: eureka
    
  # CREDITO #
  credito:
    extends:
      file: './credito/credito.yml'
      service: credito
    links: 
    - dbcredito
    restart: on-failure
    depends_on:
      - eureka
      - dbcredito
  dbcredito:
    extends:
      file: './credito/database.yml'
      service: dbcredito
    restart: on-failure

  # DEBITO #
  debito:
    extends:
      file: './debito/debito.yml'
      service: debito
    links: 
    - dbdebito
    depends_on:
      - credito
      - dbdebito
    restart: on-failure
  dbdebito:
    extends:
      file: './debito/database.yml'
      service: dbdebito
    restart: on-failure
    
  # CONTACORRENTE #
  contacorrente:
     extends:
       file: './contacorrente/contacorrente.yml'
       service: contacorrente
     links:
     - dbcontacorrente
     - credito
     - debito
     restart: on-failure
     depends_on:
      - debito
      - dbcontacorrente
  dbcontacorrente:
    extends:
      file: './contacorrente/database.yml'
      service: dbcontacorrente
    restart: on-failure

  # FATURA #
  fatura:
    extends:
      file: './fatura/fatura.yml'
      service: fatura
    links:
      - dbfatura
      - credito
      - debito
      - contacorrente
    restart: on-failure
    depends_on:
      - contacorrente
      - dbfatura
  dbfatura:
    extends:
      file: './fatura/database.yml'
      service: dbfatura
    restart: on-failure

  # INVESTIMENTO #
  investimento:
    extends:
      file: './investimento/investimento.yml'
      service: investimento
    links: 
    - dbinvestimento
    - credito
    - debito
    restart: on-failure
    depends_on:
      - fatura
      - dbinvestimento
  dbinvestimento:
    extends:
      file: './investimento/database.yml'
      service: dbinvestimento
    restart: on-failure

  # PROMETHEUS #
  prometheus:
    image: natasilva01/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - net-driver
    links: 
    - credito
    - debito
    - investimento

  # API-GATEWAY #
  apigateway:
    image: natasilva01/api-gateway
    container_name: api-gateway
    ports:
      - '9000:9000'
    networks:
      - net-driver
    depends_on:
      - prometheus

  
networks:
  net-driver:
    driver: bridge
