version: '3.5'
services:

  dbcontacorrente:
    image: mysql
    container_name: dbcontacorrente
    hostname: dbcontacorrente
    restart: always
    networks:
      - net-driver
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacorrentedb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
