version: '3.5'
services:

  dbfatura:
    image: mysql
    container_name: dbfatura
    hostname: dbfatura
    restart: always
    networks:
      - net-driver
    ports:
      - '3303:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: faturadb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
